// components/base/BaseLink/BaseLink.vue
<template lang="pug">
  component(
    v-bind='getTag'
    :class='[`base-link_theme_${theme}`, `${isButton ? "btn" : ""}`]'
    @click='onClick'
    ).base-link.link
    span.base-link__content
      slot
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  export interface IBaseLinkDownload {
    is: string;
    href: string;
    download: string;
  }

  export interface IBaseLinkExternal {
    is: string;
    href: string;
    target: string;
    rel: string;
  }

  export interface IBaseLinkRoute {
    is: string;
    to: string;
  }

  export interface IBaseLinkButton {
    is: string;
    type: string;
  }

  const BaseLinkProps = Vue.extend({
    props: {
      to: {
        type: String,
        default: '',
      },
      theme: {
        type: String,
        default: 'default',
      },
      isButton: {
        type: Boolean,
        default: false,
      },
      type: {
        type: String,
        default: 'button',
      },
    },
  });

  @Component({
    name: 'BaseLink',
  })
  export default class BaseLink extends BaseLinkProps {
    public onClick(): void {
      this.$emit('click');
    }

    public get getTag(): IBaseLinkDownload | IBaseLinkExternal | IBaseLinkRoute | IBaseLinkButton {
      const isButton = this.isButton;

      if (isButton) {
        return {
          is: 'button',
          type: this.type,
        };
      }

      const url = this.to;
      if (url.match(/([a-zA-Z0-9\s_\\.\-():])+(.doc|.docx|.pdf|.zip|.rar|.7z|xlsx)$/)) {
        return {
          is: 'a',
          href: url,
          download: '',
        };
      } else if (url.match(/^(http(s)?|ftp):\/\//)) {
        return {
          is: 'a',
          href: url,
          target: '_blank',
          rel: 'noopener noreferrer nofollow',
        };
      }

      return {
        is: 'nuxt-link',
        to: url,
      };
    }
  }
</script>

<style lang="sass">
  @import "BaseLink"
</style>

// components/base/BaseLink/BaseLink.tsx
import { VueComponent } from 'types/vue-components';
import { Prop, Component, Emit } from 'nuxt-property-decorator';
import { ButtonTypes } from 'common/types/button-types';

import './BaseLink.sass';

export type IBaseLinkThemes = 'default' | 'gray';

export interface IBaseLinkProps {
  theme?: IBaseLinkThemes;
  onClick?: () => void;
}

export interface IBaseLinkPropsWithLink extends IBaseLinkProps {
  to: string;
  isButton?: never;
  type?: never;
}

export interface IBaseLinkPropsWithButton extends IBaseLinkProps {
  to?: never;
  isButton: boolean;
  type?: ButtonTypes;
}

export type IConditionalBaseLinkProps = IBaseLinkPropsWithLink | IBaseLinkPropsWithButton;

@Component({
  name: 'BaseLink',
})
export default class BaseLink extends VueComponent<IConditionalBaseLinkProps> {
  @Prop({ default: 'default' })
  private theme!: IBaseLinkProps['theme'];

  @Prop()
  private to!: IBaseLinkPropsWithLink['to'];

  @Prop()
  private isButton!: IBaseLinkPropsWithButton['isButton'];

  @Prop({ default: 'button' })
  private type!: IBaseLinkPropsWithButton['type'];

  @Emit('click')
  public onClick(): void {}

  public render() {
    const linkComponentDefaultProps = {
      theme: this.theme,
      class: `link base-link base-link_theme_${this.theme} ${this.isButton ? 'btn' : ''}`,
      on: {
        click: this.onClick,
      },
    };
    const linkComponentContent = <span className='base-link__content'>{this.$slots.default}</span>;
    const isButton = this.isButton;
    const url = this.to;

    // Button link
    if (isButton) {
      return (
        <button {...linkComponentDefaultProps} type={this.type}>
          {linkComponentContent}
        </button>
      );
    }

    // Download link
    if (url.match(/([a-zA-Z0-9\s_\\.\-():])+(.doc|.docx|.pdf|.zip|.rar|.7z|xlsx)$/)) {
      return (
        <a {...linkComponentDefaultProps} href={url} download>
          {linkComponentContent}
        </a>
      );
      // External Link
    } else if (url.match(/^(http(s)?|ftp):\/\//)) {
      return (
        <a {...linkComponentDefaultProps} href={url} target='_blank' rel='noopener noreferrer nofollow'>
          {linkComponentContent}
        </a>
      );
    }

    // Route link
    return (
      <nuxt-link {...linkComponentDefaultProps} to={url}>
        {linkComponentContent}
      </nuxt-link>
    );
  }
}
